<?php
/**
 * @By Alain Landry Noutchomwo
 * @Alias Zumento
 * @Email alinolandry@gmail.com
 *
 */

/**
 * @var \Zumento\GiftCard\ViewModel\FrontendDetails $details
 */

use Zumento\GiftCard\Constants;

$details = $block->getData('details');
?>

<?php if ($details->getIsCustomAllowed()): ?>
    <label for="amount"><?= __('Zumento GiftCard Amount') ?></label>
    <input type="text" name="<?= Constants::OPTION_AMOUNT ?>" id="amount" value="<?= rand(5,100) ?>" placeholder="Amount" />
<?php endif; ?>

<label for="recipient-name"><?= __('Recipient name') ?></label>
<input type="text" name="<?= Constants::OPTION_RECIPIENT_NAME ?>" id="recipient-name" value="godsplan" placeholder="Recipient name" />

<label for="recipient-email"><?= __('Recipient email') ?></label>
<input type="email" name="<?= Constants::OPTION_RECIPIENT_EMAIL ?>" id="recipient-email" value="godsplan@value.com" placeholder="Recipient email" />


